### ISSUE TITLE
USER STORY SearchBar Posts

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#10]
As a **user**, I can **search for posts with keywords** so that **I can find the posts and user profiles I am most interested in.**

#### Acceptance Criteria:
- Users can view a search bar and use it to navigate the site.

#### Tasks:

- [x] Implement the search bar to the PostsPage component with filters and keywords to posts into the home, feed, and liked pages
- [x] Add the form from React Bootstrap
- [x] setTimeOut to fetchPosts for better UI
