### ISSUE TITLE
USER STORY  Create Comment Form

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#14]
As a **user**, I can **add comments to a post**, so that **I can share my thoughts about the post**.

#### Acceptance Criteria:
- Allow users to comment on the post and event.

#### Tasks:
- [x] Implement comment form
- [x] Implement a comment form to post and handle submit
- [x] Implement a comment form to event and handle submit
- [x] Save comment to post view
- [x] Save comment to event view

#### BUG
- [x] **TypeError: setPost and setEvent are not a function**
- [x] In Post comment field the event value stays undefined in the console
- [x] In Event comment field the post value stays undefined in the console
- [x] Comment input field remains the recent content after submitting it
- [x] comments are being displayed after submission
