### ISSUE TITLE
USER STORY Comment view

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#15]
As a **user**, I can **read comments left by users under the post**, so that **I can be in touch with the community**.

#### Acceptance Criteria:

- Users can view all comments associated with a post.

#### Tasks:
- [x] Create a comment view on the post details page
- [x] Implement infinite scroll to auto-update content
- [x] Display comments in order of most recents
