### ISSUE TITLE
USER STORY Profile Page & Stats

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#19]
As a **user**, I can **view basic profile information like profile picture and name,** so that **I can easily check a user's profile page.**

#### Acceptance Criteria:
- Generate a page that populates with profile data stats

#### Tasks:
- [x] Build a view page for profile details
- [x] Make username clickable to generate a new view
- [x] Populate the page with selected user data
- [x] Implement stats on individual profile page
- [x] Implement follow/unfollow button
