### ISSUE TITLE
USER STORY Follow / Unfollow Profiles

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#20]
As a **logged-in user**, I can **follow/unfollow other users,** so that **I can see and remove posts by specific users in my post feed**.

#### Acceptance Criteria:
- As a user, I can see the follow/unfollow button.

#### Tasks:
- [x] Visible Follow/unfollow button for user only
- [x] Update button to reflect follow status

##### Following:
- [x] Number of people that the user is being followed by will increase
- [x] Number of people that I am following will also increase

##### Unfollowing:
- [x] Number of people that the user unfollowed by will decrease
- [x] Number of people that I am unfollowing will also decrease
