### ISSUE TITLE
USER STORY Edit Profile

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#23]
As a **user**, I can **edit my profile**, so that **I can update or change my information**.

#### Acceptance Criteria:
- Implement profile editing feature with dropdown menu, pre-filled form, database save, and seamless redirection to the profile page.
#### Tasks:
- [x] Add Profile Dropdown Menu
- [x] Create a view form to update data
- [x] Populate form with existing data
- [x] Save form data to the database
- [x] Route user back to profile page
