### ISSUE TITLE
USER STORY Avatar View

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#26]
As a **user**, I can **view other people's avatars** so that **I can easily recognise others.**

#### Acceptance Criteria:
- View other user avatars.

#### Tasks:
- [x] Avatar available on comments
- [x] Avatar available on posts
- [x] Avatar available on events
- [x] Avatar available on profiles
- [x] Avatar available most popular list
