### ISSUE TITLE
USER STORY Edit Event

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#28]
As a **user,** I would like to **edit my event** so that **I can amend details where needed.**

#### Acceptance Criteria:
- Load existing event details & allow users to input new values.

#### Tasks:
- [x] Supply template to input new values
- [x] Populate template with existing values
- [x] Push new values to API
- [x] Provide a drop-down menu button on the event page to navigate to the edit page
