### ISSUE TITLE
USER STORY Delete Event

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#29]
As a **user,** I would like to **delete an event** so that I can **remove events that are no longer happening**.

#### Acceptance Criteria:
- Remove permanently the event from the API.

#### Tasks:
- [ ] Provide a drop-down menu button to the user to delete the event
- [ ] Provide warning to confirm deletion
- [ ] Remove event data from API
- [ ] Route the user to the previous page upon completion
