### ISSUE TITLE
USER STORY Authentication SignUp

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#3]
As a **user**, **I can** create a new account, **so that** I can access all the features for the signed-up users.

#### Acceptance Criteria:
- successfully create a new account
#### Tasks:

- [x]  Sign up button
- [x]  Form to register
- [x]  Re-route back to home-page
