### ISSUE TITLE
USER STORY Events List

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#30]
As a **user**, I would like to **see all events** so that **I can browse all of the events occurring.**

#### ACCEPTANCE CRITERIA:
- Able to view all events on a page

#### TASKS:
- [x] Load all event data from the API
- [x] Populate the page in descending order, with recent events created appearing at the top
- [x] Implement NavBar button to navigate to the event page

#### Bug Ticket

- [x] Fix events API ordering by created_on
