### ISSUE TITLE
USER STORY Search Events

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#31]
As a **user,** I would like to **search all existing events** so that **I can find events near me, title, category, or by username.**

#### Acceptance Criteria:
- Search through events by title, place, category, or username of the creator.

#### Tasks:
- [x] Search bar at the top of the events page
- [x] Filter results by owner, title, place and category
- [x] Events list results to user
