### ISSUE TITLE
USER STORY Like/Unlike Posts

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#32]
USER STORY:
As a **user,** I can **like/unlike a post** so that **I can show my interactive appreciation of the content.**

#### Acceptance Criteria:
- A clickable like a button that will allow users to like/unlike with the click of a button.

#### Tasks:
- [x] Like/unlike button
- [x] Update database with new information
- [x] Handle like count to update on the post page once increased
- [x] Handle unlike count to update on the post page once decreased
