### ISSUE TITLE
USER STORY Save/unsaved Events

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#33]
USER STORY:
As a **user,** I can **save/unsaved an event** so that **I can access easily back the events that I'm interested in.**

#### Acceptance Criteria:
- A clickable save button that will allow users to save/unsaved with the click of a button.

#### Tasks:
- [x] Saved/unsaved button
- [x] Update database with new information
- [x] Handle save count to update on the event page once increased
- [x] Handle unsaved count to update on the event page once decreased
