### ISSUE TITLE
USER STORY About Page

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#35]
As a **user**, I can **visit and view the About page**, so that **I can see a clear and concise description of the platform's purpose and features.**

#### Acceptance Criteria:
- As a user, I expect the About page to provide information on how to share photos, discover content, join events, and connect with other photographers.
#### Tasks
- [x] Create About page
- [x] Add into the NavBar
- [x] Add social icons
- [x] Add sign up button
