### ISSUE TITLE
USER STORY Saved Event List

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#36]
As a **user**, I can **view all the events that I have saved** so that I can **quickly browse through my saved content.**

#### Acceptance Criteria:
- A new page view to display all events a user has saved.

#### Tasks:
- [x] Implement in NavBar link to access the saved view page
- [x] Create a new display page
- [x] Populate the page with events the user has saved
