### ISSUE TITLE
USER STORY PostList

### ISSUE THREAD

**Issue by patthoege** [patthoege/pp5-exposurep#9]
As a **user**, I can **view all the most recent posts,** so that **I can I am up to date with the newest content.**

#### Acceptance Criteria:
- Users can view a particular post on a single page along with additional information about the post and browse through comments.

#### Tasks:
- [x] Create PostsPage to display the content  from the database
- [x] Add a PostsPage module CSS to the styles folder
- [x] Add a no-results image to the assets folder
